version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Webhook_Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
